---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: lansible/zigbee2mqtt
    build_args:
      - ARCH=amd64
      - VERSION=${DRONE_TAG:-master}
    tags: ${DRONE_TAG:-master}-amd64

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: lansible/zigbee2mqtt
    build_args:
      - ARCH=amd64
      - VERSION=${DRONE_TAG:-master}
    tags: ${DRONE_TAG:-master}-amd64
