---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: docker
  environment:
    DOCKER_NAMESPACE: lansible
    CONTAINER_NAME: zigbee2mqtt
  commands:
    - export ARCH=$(echo ${DRONE_RUNNER_PLATFORM} | cut -d '/' -f 2)
    - echo $ARCH
    - export VERSION=${DRONE_TAG:-$DRONE_BRANCH}
    - echo $VERSION
    - docker build .
        --build-arg VERSION=$VERSION
        --tag $DOCKER_NAMESPACE/$CONTAINER_NAME:$VERSION-$ARCH

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: docker
  environment:
    DOCKER_NAMESPACE: lansible
    CONTAINER_NAME: zigbee2mqtt
  commands:
    - export ARCH=$(echo ${DRONE_RUNNER_PLATFORM} | cut -d '/' -f 2)
    - echo $ARCH
    - export VERSION=${DRONE_TAG:-$DRONE_BRANCH}
    - echo $VERSION
    - docker build .
        --build-arg VERSION=$VERSION
        --tag $DOCKER_NAMESPACE/$CONTAINER_NAME:$VERSION-$ARCH
