---
dist: xenial
language: minimal

env:
  global:
    - fast_finish: true
    - DOCKER_NAMESPACE=lansible
    - CONTAINER_NAME=zigbee2mqtt

services:
  - docker

matrix:
  include:
    # amd64
    - env: VERSION=${TRAVIS_TAG:-1.4.0} ARCH=amd64

    # arm64
    - env: VERSION=${TRAVIS_TAG:-1.4.0} ARCH=arm64

before_script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # Pipe to true since the tag could be non existing
  - docker pull ${DOCKER_NAMESPACE}/${CONTAINER_NAME}:${VERSION}-${ARCH} || true
  - docker pull ${DOCKER_NAMESPACE}/${CONTAINER_NAME}:latest || true

script:
  # Build Zigbee2MQTT container
  - docker build .
      --build-arg ARCH=${ARCH}
      --build-arg VERSION=${VERSION}
      --cache-from ${DOCKER_NAMESPACE}dump/${CONTAINER_NAME}:latest
      --cache-from ${DOCKER_NAMESPACE}/${CONTAINER_NAME}:${VERSION}-${ARCH}
      --tag ${DOCKER_NAMESPACE}/${CONTAINER_NAME}:${VERSION}-${ARCH}

#TODO: Write a test stage

deploy:
  provider: script
  script: deploy/deploy.sh
  on:
    branch: master
  skip_cleanup: true

notifications:
  email:
    on_failure: change
    on_success: never
