---
  version: "3"
  services:
    zigbee2mqtt:
      container_name: zigbee2mqtt
      image: lansible/zigbee2mqtt:latest
      volumes:
        - ./config:/config
      devices:
        - /dev/ttyACM0:/dev/ttyACM0
      restart: always
